
GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

--食物
STRINGS.NAMES.STEAMEDHAMSANDWICH = "蒸火腿三明治"

STRINGS.NAMES.ALOE = "芦荟"
STRINGS.NAMES.ALOE_COOKED = "熟芦荟"
STRINGS.NAMES.ALOE_SEEDS = "芦荟种子"

STRINGS.NAMES.ASPARAGUS = "芦笋"
STRINGS.NAMES.ASPARAGUS_COOKED = "熟芦笋"
STRINGS.NAMES.ASPARAGUS_SEEDS = "芦笋种子"
STRINGS.NAMES.ASPARAGUSSOUP = "芦荟汤"
STRINGS.NAMES.SPICYVEGSTINGER = "蔬菜鸡尾酒"

STRINGS.NAMES.RADISH = "红萝卜"
STRINGS.NAMES.RADISH_COOKED = "熟红萝卜"
STRINGS.NAMES.RADISH_SEEDS = "红萝卜种子"

STRINGS.NAMES.TEA = "茶"
STRINGS.NAMES.ICEDTEA = "冰茶"

STRINGS.NAMES.JELLYBUG = "豆虫"
STRINGS.NAMES.JELLYBUG_COOKEF = "熟豆虫"
STRINGS.NAMES.JELLYBUG_SEEDS = "豆虫种子"
STRINGS.NAMES.SLUGBUG = "蛞蝓"
STRINGS.NAMES.SLUGBUG_COOKED = "熟蛞蝓"

STRINGS.NAMES.GUMMY_CAKE = "软糖蛋糕"
STRINGS.RECIPE_DESC.GUMMY_CAKE = "动画存在问题\n所以改为制作"
STRINGS.NAMES.FEIJOADA = "巴西肉烧豆"
STRINGS.NAMES.HARDSHELL_TACOS = "硬壳卷饼"

--狮鼻蛇怪
STRINGS.NAMES.SNAKEBONESOUP = "蛇骨汤"
STRINGS.NAMES.BONESTAFF = "蛇王骨杖"
STRINGS.RECIPE_DESC.BONESTAFF = "持续6秒的冻感光波"
STRINGS.NAMES.PUGALISK_FOUNTAIN = "不老泉"
STRINGS.NAMES.FLOWEROFLIFE = "魔术花"
STRINGS.NAMES.WATERDROP = "魔法水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUGALISK = {"它的皮太硬了!", "难以打破的磷甲。", "碎掉，该死的！"}

--利齿捕蝇草
STRINGS.NAMES.MEAN_FLYTRAP = "利齿幼苗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEAN_FLYTRAP = "很显然，这是个孩子。肉对它有很大的吸引力。"
STRINGS.NAMES.ADULT_FLYTRAP = "利齿捕蝇草"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ADULT_FLYTRAP = "嘘。它正在睡觉。"
STRINGS.NAMES.VENUS_STALK = "捕蝇草茎"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VENUS_STALK = "我敢打赌我一定能找到它的用处。"
STRINGS.NAMES.WALKINGSTICK = "花柄手杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALKINGSTICK = "不可思议！它让我的速度刚好提高了百分之三十！"

--荆棘
STRINGS.NAMES.BRAMBLE = "荆棘丛"
STRINGS.NAMES.BRAMBLESPIKE = "荆棘"
STRINGS.NAMES.BRAMBLE_CORE = "荆棘花"
STRINGS.NAMES.BRAMBLESITE = "荆棘未知"

STRINGS.NAMES.BRAMBLE_BULB = "荆棘花朵"
STRINGS.RECIPE_DESC.BRAMBLE_BULB = "临时使用 待完善"

STRINGS.NAMES.ARMOR_BRAMBLE = "荆棘甲"
STRINGS.RECIPE_DESC.ARMOR_BRAMBLE =  "尖尖的盔甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_BRAMBLE = "尖尖的盔甲。"

STRINGS.NAMES.TRAP_BRAMBLE = "荆棘陷阱"
STRINGS.RECIPE_DESC.TRAP_BRAMBLE =  "用朋友做了一个陷阱！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAP_BRAMBLE = "这个陷阱是荆棘做的！"

--路灯和打包纸
STRINGS.NAMES.CITY_LAMP = "路灯"
STRINGS.RECIPE_DESC.CITY_LAMP = "我不敢相信我能做到"

STRINGS.NAMES.BEESWAX = "蜂蜡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEESWAX = "蜂蜡是公认的保鲜剂"
STRINGS.RECIPE_DESC.BEESWAX = "有用的保鲜蜡"

STRINGS.NAMES.WAXPAPER = "蜡纸"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXPAPER = "几张蜡纸"
STRINGS.RECIPE_DESC.WAXPAPER = "用来制作打包纸"

STRINGS.NAMES.BUNDLE = "打包纸"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUNDLE = { EMPTY = "空的，快放着东西进来.", FILLED = "里面似乎装着一些东西"}
STRINGS.RECIPE_DESC.BUNDLE = "用来打包你的东西."

--哈姆雷特装备
STRINGS.NAMES.BLUNDERBUSS = "火枪"
STRINGS.RECIPE_DESC.BLUNDERBUSS = "加火药可远程"

STRINGS.NAMES.CANDLEHAT = "软木蜡烛帽"
STRINGS.RECIPE_DESC.CANDLEHAT = "小范围照明"

STRINGS.NAMES.CORK_BAT = "软木棒"
STRINGS.RECIPE_DESC.CORK_BAT = "比火腿棒强"

STRINGS.NAMES.SNAKESKINHAT = "蛇皮帽"
STRINGS.RECIPE_DESC.SNAKESKINHAT = "另外一种蛇皮帽"

STRINGS.NAMES.ARMOR_SNAKESKIN_SCALY = "蛇皮衣"
STRINGS.RECIPE_DESC.ARMOR_SNAKESKIN_SCALY = "另外一种蛇皮衣"

STRINGS.NAMES.ARMOR_WEEVOLE = "象鼻虫甲"
STRINGS.RECIPE_DESC.ARMOR_WEEVOLE = "不会加速的大理石甲"

STRINGS.NAMES.HALBERD = "戟"
STRINGS.RECIPE_DESC.HALBERD = "可以当斧头"

STRINGS.NAMES.ANTSUIT = "蚂蚁甲"
STRINGS.RECIPE_DESC.ANTSUIT = "蚂蚁壳做的甲"

STRINGS.NAMES.METALPLATEHAT = "花顶头盔"
STRINGS.RECIPE_DESC.METALPLATEHAT = "用锡做的头盔"

STRINGS.NAMES.ARMOR_METALPLATE = "锡甲"
STRINGS.RECIPE_DESC.ARMOR_METALPLATE = "用锡做的甲"

STRINGS.NAMES.ANTMASKHAT = "蚂蚁头盔"
STRINGS.RECIPE_DESC.ANTMASKHAT = "蚂蚁壳做的头盔"

STRINGS.NAMES.THUNDERHAT = "避雷帽"
STRINGS.RECIPE_DESC.THUNDERHAT = "可躲避十次雷"

STRINGS.NAMES.PITHHAT = "探险帽"
STRINGS.RECIPE_DESC.PITHHAT = "未知"

STRINGS.NAMES.GASMASKHAT = "防毒面具"
STRINGS.RECIPE_DESC.GASMASKHAT = "可以防毒"

STRINGS.NAMES.PIGCROWNHAT = "猪王冠"
STRINGS.RECIPE_DESC.PIGCROWNHAT = "只能回复精神值…"

--松鼠和象鼻虫
 STRINGS.NAMES.PIKO_ORANGE = "松鼠"
 STRINGS.NAMES.PIKO = "灰松鼠"
 
 STRINGS.NAMES.WEEVOLE = "象鼻虫"
 STRINGS.NAMES.WEEVOLE_CARAPACE = "象鼻虫壳"

--茶树
 STRINGS.NAMES.TEATREE = "茶树"
 STRINGS.NAMES.TEATREE_NUT = "茶树种子"
 STRINGS.NAMES.TEATREE_NUT_COOKED = "熟茶树种子"
 STRINGS.NAMES.TEATREE_SAPLING = "茶树苗"
 
--蠕虫和蝎子
 STRINGS.NAMES.GIANTGRUB = "大蠕虫"
 STRINGS.NAMES.SCORPION = "蝎子"
 STRINGS.NAMES.CHITIN = "虫壳"
 
--曼德拉长老
STRINGS.NAMES.MANDRAKEMAN = "曼德拉长老"
STRINGS.NAMES.MANDRAKEHOUSE = "曼德拉丘"

STRINGS.MANDRAKEMAN_BATTLECRY = {"腐败！", "泥土！", "肥料！", "腐殖土！"}
STRINGS.MANDRAKEMAN_GIVEUP = {"你要干什么？", "真累", "好困", "累坏了"}
STRINGS.MANDRAKEMAN_MANDRAKE_BATTLECRY = {"小偷！", "强盗！", "坏蛋！", "骗子！"}
STRINGS.MANDRAKEMAN_RETREAT = {"走开！", "痛！", "回家！", "快跑！"}

--雷鸟
STRINGS.NAMES.THUNDERBIRD = "雷鸟"
STRINGS.NAMES.THUNDERBIRDNEST = "雷鸟巢穴"

--睡莲
STRINGS.NAMES.LOTUS = "睡莲苗"
STRINGS.RECIPE_DESC.LOTUS = "栽培可爱的小莲花！"

STRINGS.NAMES.LILYPAD = "睡莲叶"
STRINGS.RECIPE_DESC.LILYPAD = "打造你的莲花池塘！"
	
STRINGS.NAMES.LOTUS_FLOWER = "莲花"
STRINGS.NAMES.LOTUS_FLOWER_COOKED = "莲藕"

--重击者
STRINGS.NAMES.THUMPER = "重击者"
STRINGS.RECIPE_DESC.THUMPER = "革命性的收割机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THUMPER = "让我所有的劳动结晶为我工作吧。"

--钢铁巨兽
STRINGS.NAMES.LIVING_ARTIFACT = "钢铁战衣"
STRINGS.RECIPE_DESC.LIVING_ARTIFACT = "铠甲合体！"
STRINGS.NAMES.ANCIENT_HULK = "机械巨兽"
STRINGS.NAMES.ANCIENT_ROBOTS_ASSEMBLY = "废铁堆"
STRINGS.NAMES.ANCIENT_ROBOT_CLAW = "机械爪子"
STRINGS.NAMES.ANCIENT_ROBOT_HEAD = "机械头部"
STRINGS.NAMES.ANCIENT_ROBOT_LEG = "机械腿部"
STRINGS.NAMES.ANCIENT_ROBOT_RIBS = "机械躯体"
STRINGS.NAMES.ROCK_BASALT = "岩石"
STRINGS.NAMES.INFUSED_IRON = "激发态铁"
STRINGS.NAMES.ALLOY = "铁块"
STRINGS.NAMES.IRON = "铁"
STRINGS.NAMES.SMELTER = "熔炉"
STRINGS.RECIPE_DESC.SMELTER = "把铁变成铁块"

--远古先驱
STRINGS.NAMES.ANCIENT_HERALD = "远古先驱"
STRINGS.NAMES.ANCIENT_REMNANT = "暗影飞镖"
STRINGS.NAMES.ARMORVORTEXCLOAK = "暗影斗篷"
STRINGS.RECIPE_DESC.ARMORVORTEXCLOAK = "斗篷背包里有噩梦燃料\n可自动修复耐久"

--蚁后和蚂蚁
STRINGS.NAMES.ANTQUEEN = "蚁后"
STRINGS.NAMES.ANTQUEEN_THRONE = "蚁后王座"

STRINGS.NAMES.ANTCOMBHOME = "蚂蚁巢穴"
STRINGS.NAMES.ANTMAN = "蚁人"
STRINGS.NAMES.ANTMAN_WARRIOR = "蚂蚁战士"
STRINGS.NAMES.ANTMAN_WARRIOR_EGG = "蚂蚁卵"

--虫木
STRINGS.RECIPE_DESC.LIVINGLOG = "减少20生命值"
STRINGS.NAMES.COMPOSTWRAP = "肥料包"
STRINGS.RECIPE_DESC.COMPOSTWRAP = "便便有益身心健康"
STRINGS.NAMES.POISONBALM = "解毒剂"
STRINGS.RECIPE_DESC.POISONBALM = "远离病害"

STRINGS.CHARACTER_TITLES.wormwood = "沃姆伍德"
STRINGS.CHARACTER_NAMES.wormwood = "wormwood"
STRINGS.CHARACTER_DESCRIPTIONS.wormwood = "*植物与他有关\n*种子可直接种植在地面\n*食物填饱了他的胃，却填不饱他的心"
STRINGS.CHARACTER_QUOTES.wormwood = "\"你好，朋友？\""

STRINGS.NAMES.DECO_RUINS_FOUNTAIN = "许愿池"
STRINGS.NAMES.DECO_RUINS_ENDSWELL = "末日井"

STRINGS.NAMES.TURF_COBBLEROAD = "砖石路"
STRINGS.RECIPE_DESC.TURF_COBBLEROAD = "承载着村庄繁荣生活。"

STRINGS.NAMES.TURF_DEEPRAINFOREST = "密林地皮"
STRINGS.RECIPE_DESC.TURF_DEEPRAINFOREST = "疏影暗香藏隐士，密林深处有人居。"

STRINGS.NAMES.TURF_FIELDS = "耕地地皮"
STRINGS.RECIPE_DESC.TURF_FIELDS = "孕育着文明。"

STRINGS.NAMES.TURF_FOUNDATION = "地基地面"
STRINGS.RECIPE_DESC.TURF_FOUNDATION = "村庄建设的坚实基础。"

STRINGS.NAMES.TURF_GASJUNGLE = "毒性地皮"
STRINGS.RECIPE_DESC.TURF_GASJUNGLE = "瘴气丛林。"

STRINGS.NAMES.TURF_LAWN = "方格草坪"
STRINGS.RECIPE_DESC.TURF_LAWN = "严格修整的草坪。"

STRINGS.NAMES.TURF_MOSS = "苔藓地皮"
STRINGS.RECIPE_DESC.TURF_MOSS = "白日不到处，青春恰自来。"

STRINGS.NAMES.TURF_PIGRUINS = "遗迹地皮"
STRINGS.RECIPE_DESC.TURF_PIGRUINS = "的确是有些历史了。"

STRINGS.NAMES.TURF_RAINFOREST = "雨林地皮"
STRINGS.RECIPE_DESC.TURF_RAINFOREST = "哦，雨林。"