
GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

	local seg_time = 30 --each segment of the clock is 30 seconds
	local total_day_time = seg_time*16

	local day_segs = 10
	local dusk_segs = 4
	local night_segs = 2

	--default day composition. changes in winter, etc
	local day_time = seg_time * day_segs
	local dusk_time = seg_time * dusk_segs
	local night_time = seg_time * night_segs

	local wilson_attack = 34
	local wilson_health = 150
	local calories_per_day = 75

	local wilson_attack_period = .5
	
--狮鼻蛇怪
TUNING.PUGALISK_HEALTH = 3000
TUNING.PUGALISK_ATTACK_PERIOD = 3
TUNING.PUGALISK_MELEE_RANGE = 6
TUNING.PUGALISK_DAMAGE = 200
TUNING.PUGALISK_TARGET_DIST = 40
TUNING.PUGALISK_TAIL_TARGET_DIST = 6
TUNING.PUGALISK_RUINS_PILLAR_WORK = 3
	
--利齿捕蝇草
	TUNING.FLYTRAP_CHILD_HEALTH = 250
	TUNING.FLYTRAP_CHILD_DAMAGE = 15
 TUNING.FLYTRAP_CHILD_SPEED = 4

	TUNING.FLYTRAP_TEEN_HEALTH = 300
	TUNING.FLYTRAP_TEEN_DAMAGE = 20
	TUNING.FLYTRAP_TEEN_SPEED = 3.5

 TUNING.FLYTRAP_HEALTH = 350
 TUNING.FLYTRAP_DAMAGE = 25
 TUNING.FLYTRAP_SPEED = 3

	TUNING.FLYTRAP_TARGET_DIST = 8
	TUNING.FLYTRAP_KEEP_TARGET_DIST= 15
	TUNING.FLYTRAP_ATTACK_PERIOD = 3

	TUNING.ADULT_FLYTRAP_HEALTH = 400
	TUNING.ADULT_FLYTRAP_DAMAGE = 30
	TUNING.ADULT_FLYTRAP_ATTACK_PERIOD = 5
	TUNING.ADULT_FLYTRAP_ATTACK_DIST = 4
	TUNING.ADULT_FLYTRAP_STOPATTACK_DIST = 6
	
	TUNING.WALKING_STICK_DAMAGE = 34*.6
	TUNING.WALKING_STICK_SPEED_MULT = 0.3
	TUNING.WALKING_STICK_PERISHTIME = 30*16*3
	
	--荆棘
 TUNING.BRAMBLE_THORN_DAMAGE = 3

	TUNING.TRAP_BRAMBLE_USES = 10
	TUNING.TRAP_BRAMBLE_DAMAGE = 40
	TUNING.TRAP_BRAMBLE_RADIUS = 2.5
	
 TUNING.ARMORBRAMBLE_DMG = 34/1.5
 TUNING.ARMORBRAMBLE_ABSORPTION = .65
 TUNING.ARMORBRAMBLE = 150*2.5

--松鼠和象鼻虫
 TUNING.PIKO_HEALTH = 100
	TUNING.PIKO_RESPAWN_TIME = 30*10*4
	TUNING.PIKO_RUN_SPEED = 4
	TUNING.PIKO_DAMAGE = 2
	TUNING.PIKO_ATTACK_PERIOD = 2
	TUNING.PIKO_TARGET_DIST = 20
	TUNING.PIKO_RABID_SANITY_THRESHOLD = 0.8	
	
 TUNING.WEEVOLE_WALK_SPEED = 5
 TUNING.WEEVOLE_HEALTH = 150
 TUNING.WEEVOLE_DAMAGE = 6
 TUNING.WEEVOLE_PERIOD_MIN = 4
 TUNING.WEEVOLE_PERIOD_MAX = 5
 TUNING.WEEVOLE_ATTACK_RANGE = 5
 TUNING.WEEVOLE_HIT_RANGE = 1.5
 TUNING.WEEVOLE_MELEE_RANGE = 1.5
 TUNING.WEEVOLE_RUN_AWAY_DIST = 3
 TUNING.WEEVOLE_STOP_RUN_AWAY_DIST = 5
 TUNING.WEEVOLE_TARGET_DIST = 6
 TUNING.WEEVOLEDEN_MAX_WEEVOLES = 3 

--蠕虫和蝎子  
	TUNING.GIANT_GRUB_WALK_SPEED = 2
	TUNING.GIANT_GRUB_DAMAGE = 44
	TUNING.GIANT_GRUB_HEALTH = 600
	TUNING.GIANT_GRUB_ATTACK_PERIOD = 3
	TUNING.GIANT_GRUB_ATTACK_RANGE = 3
	TUNING.GIANT_GRUB_TARGET_DIST = 25
	
	TUNING.SCORPION_HEALTH = 200
 TUNING.SCORPION_DAMAGE = 20
	TUNING.SCORPION_ATTACK_PERIOD = 3
	TUNING.SCORPION_TARGET_DIST = 4
	TUNING.SCORPION_INVESTIGATETARGET_DIST = 6
	TUNING.SCORPION_WAKE_RADIUS = 4
	TUNING.SCORPION_FLAMMABILITY = .33
	TUNING.SCORPION_SUMMON_WARRIORS_RADIUS = 12
	TUNING.SCORPION_EAT_DELAY = 1.5
	TUNING.SCORPION_ATTACK_RANGE = 3
	TUNING.SCORPION_STING_RANGE = 2
	TUNING.SCORPION_WALK_SPEED = 3
	TUNING.SCORPION_RUN_SPEED = 5

--曼德拉长老
	    TUNING.MANDRAKEMAN_DAMAGE = 40
	    TUNING.MANDRAKEMAN_HEALTH = 200
	    TUNING.MANDRAKEMAN_ATTACK_PERIOD = 2
	    TUNING.MANDRAKEMAN_RUN_SPEED = 6
	    TUNING.MANDRAKEMAN_WALK_SPEED = 3
		TUNING.MANDRAKEMAN_PANIC_THRESH = .333
		TUNING.MANDRAKEMAN_HEALTH_REGEN_PERIOD = 5
		TUNING.MANDRAKEMAN_HEALTH_REGEN_AMOUNT = (200/120)*5
		TUNING.MANDRAKEMAN_SEE_MANDRAKE_DIST = 8
		TUNING.MANDRAKEMAN_TARGET_DIST = 10
		TUNING.MANDRAKEMAN_DEFEND_DIST = 30

--睡莲
TUNING.BILL_SPAWN_CHANCE = 0.2

TUNING.LOTUS_REGROW_TIME = 30*16*5


TUNING.POND_REGEN_TIME = 30*10/2
TUNING.POND_SPAWN_TIME = 30*10/4
		

TUNING.MOSQUITO_MAX_SPAWN = 1
TUNING.MOSQUITO_REGEN_TIME = 30*10/2
TUNING.FROG_POISON_MAX_SPAWN = 1
TUNING.FROG_POISON_REGEN_TIME = 30*10/2

--钢铁巨兽
	 TUNING.ANCIENT_HULK_DAMAGE = 200
	 TUNING.ANCIENT_HULK_MINE_DAMAGE = 100
	 TUNING.ANCIENT_HULK_MELEE_RANGE = 5.5
		TUNING.ANCIENT_HULK_ATTACK_RANGE = 5.5
		
  TUNING.ROBOT_TARGET_DIST = 15
	 TUNING.ROBOT_RIBS_DAMAGE = 34 
	 TUNING.ROBOT_RIBS_HEALTH = 1000
	 TUNING.ROBOT_LEG_DAMAGE = 34*2 
	 TUNING.PERISH_APORKALYPSE_MULT = 1.5
	 TUNING.LASER_DAMAGE = 20
	 TUNING.INFUSED_IRON_PERISHTIME = 30*16*2 
	 
		TUNING.IRON_LORD_DAMAGE = 34*2 
		TUNING.IRON_LORD_TIME = 3*60
